# Package specification, as defined here:
# https://packaging.python.org/en/latest/specifications/pyproject-toml/#pyproject-toml-spec

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["src*"]

[project]
name = "think-overflow"
readme = "README.md"
version = "0.dev0"
authors = [{ name = "Lukas Twist", email = "itsluketwist@gmail.com" }]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.11"

[tool.pytest.ini_options]
# suppress INFO-level log messages from vllm and other noisy libraries
log_level = "WARNING"

[project.scripts]
run = "src.cli:main"
